## YAML Template.
---
version: '3.3'

services:
    api:
        build:
            context: .
#            target: development
#            target: production
        image: koa_api
#        image: asia-east1-docker.pkg.dev/sevensenses-team2-koa/petarush/petarush_api
        container_name: KoaAPI
        ports: 
            - 37001:80
        volumes: 
            - ./src:/var/www/html
        environment:
            SYSENV: local
#            MAINTAIN: 'true'
            DBLABEL_MAIN: KoaMain
            DBLABEL_STATIC: KoaStatic
            DBLABEL_LOG: KoaLog
            DBLABEL_ELITE_TEST: EliteTest
            DB_HOST: db
            DB_PORT: 3306
            DB_USERNAME: root
            DB_PASSWORD: 1111
            DB_NAME: koa_main
            MEMCACHED_HOST: memcached
            MEMCACHED_PORT: 11211
#            XDEBUG_CLIENT_HOST: 192.168.3.243
#            XDEBUG_CLIENT_PORT: 9003
    memcached:
        image: memcached:1.6.9
        container_name: KoaMemcached
        ports: 
            - 39902:11211
    db:
        image: mariadb
        container_name: KoaDatabase
        ports:
            - 37002:3306
        volumes:
            - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1111
            