USE `koa_log`;

ALTER TABLE `UpgradeSkill` MODIFY COLUMN `PlayerID` BigInt NOT NULL DEFAULT 0 COMMENT '使用者編號';
ALTER TABLE `UpgradeRank` MODIFY COLUMN `PlayerID` BigInt NOT NULL DEFAULT 0 COMMENT '使用者編號';
ALTER TABLE `UpgradeLevel` MODIFY COLUMN `PlayerID` BigInt NOT NULL DEFAULT 0 COMMENT '使用者編號';
ALTER TABLE `PVECleared` MODIFY COLUMN `PlayerID` BigInt NOT NULL DEFAULT 0 COMMENT '使用者編號';