USE `koa_main`;
ALTER TABLE `PlayerNFT`
	ADD COLUMN `ExternalURL` VARCHAR(255) NULL DEFAULT NULL , 
	ADD COLUMN `Image` VARCHAR(255) NULL DEFAULT NULL  COMMENT '角色圖片',
	ADD COLUMN `AnimationURL` VARCHAR(255) NULL DEFAULT NULL  COMMENT '角色音樂網址';